apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 



kind: Deployment 



metadata: 



  name: gameoflife



spec: 



  selector: 



    matchLabels: 



      app:  gameoflife 



  replicas: 5 # tells deployment to run 2 pods matching the template 



  template:



    metadata: 



      labels: 



        app:  gameoflife



    spec: 



      containers: 



      - name:  gameoflife 



        image: gsrini23/gameoflife:$(Build.BuildId)#



        ports: 



        - containerPort: 80 



--- 



# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  



kind: Service 



apiVersion: v1 



metadata: 



  name:  gameoflife



spec: 



  selector: 



    app: gameoflife



  ports: 



  - protocol: TCP 



    port: 80 



    targetPort: 80 



  type: LoadBalancer 
