apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameoflifeadimagedeployment
  labels:
    app: gameoflifeadimage
spec:
  replicas: 6
  selector:
    matchLabels:
      app: gameoflifeadimage
  template:
    metadata:
      labels:
        app: gameoflifeadimage
    spec:
      containers:
      - name: myweb
        image: gsrini23/gameoflifeadimage:"$(version)"
        ports:
        - containerPort: 8080
