apiVersion: apps/v1

kind: Deployment

metadata:

  name: gameoflifedeployment

  labels:

    app: gameoflife

spec:

  replicas: 6

  selector:

    matchLabels:

      app: gameoflife

  template:

    metadata:

      labels:

        app: gameoflife

    spec:

      containers:

      - name: gameoflife

        image: gsrini23/releasetest:"$(version)"

        ports:

        - containerPort: 8080
