apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gameoflife
  namespace: gameoflife
  labels:
    app: gameoflife
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gameoflife
  template:
    metadata:
      labels:
        app: gameoflife
    spec:
      containers:
      - name: gameoflife
        image: hello-world
        ports:
        - containerPort: 8080
